CREATE TABLE IF NOT EXISTS `t_openai_compat_state` (
  `id` varchar(64) NOT NULL,
  `object_type` varchar(32) NOT NULL,
  `owner_type` varchar(32) NOT NULL,
  `owner_id` varchar(64) NOT NULL,
  `parent_id` varchar(64) DEFAULT NULL,
  `assistant_id` varchar(64) DEFAULT NULL,
  `role` varchar(32) DEFAULT NULL,
  `model_alias` varchar(128) DEFAULT NULL,
  `status` varchar(32) DEFAULT NULL,
  `name` varchar(255) DEFAULT NULL,
  `instructions` mediumtext,
  `content_text` mediumtext,
  `content_json` longtext,
  `output_text` mediumtext,
  `created_at` bigint NOT NULL,
  `updated_at` bigint NOT NULL,
  PRIMARY KEY (`id`),
  KEY `idx_openai_compat_owner` (`object_type`, `owner_type`, `owner_id`, `created_at`),
  KEY `idx_openai_compat_parent` (`object_type`, `parent_id`, `created_at`),
  KEY `idx_openai_compat_assistant` (`assistant_id`, `created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='OpenAI compat persistent state';
