CREATE TABLE IF NOT EXISTS `t_robotfactory_corp_mapping` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `school_id` bigint NOT NULL COMMENT '学校ID',
  `school_name_snapshot` varchar(128) DEFAULT NULL COMMENT '学校名称快照',
  `corp_id` bigint NOT NULL COMMENT '软件工厂租户ID',
  `enabled` tinyint(1) NOT NULL DEFAULT 1 COMMENT '是否启用：1启用 0停用',
  `remark` varchar(255) DEFAULT NULL COMMENT '备注',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_robotfactory_school_id` (`school_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='软件工厂学校与Corp映射表';

CREATE TABLE IF NOT EXISTS `t_robotfactory_projection` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `resource_id` bigint NOT NULL COMMENT '本平台资源ID',
  `resource_type` varchar(16) NOT NULL DEFAULT 'mcp' COMMENT '资源类型，一期固定为mcp',
  `projection_code` varchar(64) NOT NULL COMMENT '投影编码，用于兼容接口访问',
  `school_id` bigint DEFAULT NULL COMMENT '学校ID',
  `corp_id` bigint DEFAULT NULL COMMENT '软件工厂租户ID，global模式下为空',
  `scope_mode` varchar(16) NOT NULL DEFAULT 'school' COMMENT '投影范围：school/global',
  `agent_name` varchar(64) NOT NULL COMMENT '同步到软件工厂的稳定Agent标识',
  `display_name` varchar(128) DEFAULT NULL COMMENT '当前生效的显示名称',
  `description` text DEFAULT NULL COMMENT '当前生效的描述',
  `display_name_override` varchar(128) DEFAULT NULL COMMENT '管理员覆盖的显示名称',
  `description_override` text DEFAULT NULL COMMENT '管理员覆盖的描述',
  `display_template` varchar(50) DEFAULT NULL COMMENT '当前生效的展示模板',
  `display_template_override` varchar(50) DEFAULT NULL COMMENT '管理员覆盖的展示模板',
  `agent_type` varchar(20) NOT NULL DEFAULT 'mcp' COMMENT '软件工厂Agent类型',
  `mode` varchar(20) NOT NULL DEFAULT 'TOOL' COMMENT '软件工厂运行模式',
  `runtime_role` varchar(20) DEFAULT 'tool' COMMENT '软件工厂运行角色',
  `interaction_mode` varchar(20) DEFAULT 'sync' COMMENT '软件工厂交互方式',
  `dispatch_mode` varchar(20) DEFAULT 'tool_sync' COMMENT '软件工厂调度方式',
  `spec_json` longtext DEFAULT NULL COMMENT '当前生效的Agent协议定义JSON',
  `spec_json_override` longtext DEFAULT NULL COMMENT '管理员覆盖的Agent协议定义JSON',
  `parameters_schema` longtext DEFAULT NULL COMMENT '当前生效的参数Schema JSON',
  `parameters_schema_override` longtext DEFAULT NULL COMMENT '管理员覆盖的参数Schema JSON',
  `auto_sync_enabled` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否启用自动同步：1启用 0关闭',
  `external_agent_id` bigint DEFAULT NULL COMMENT '软件工厂外部Agent ID',
  `sync_status` varchar(20) NOT NULL DEFAULT 'pending' COMMENT '最近同步状态',
  `sync_message` varchar(500) DEFAULT NULL COMMENT '最近同步结果说明',
  `last_synced_at` datetime DEFAULT NULL COMMENT '最近同步时间',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_robotfactory_resource` (`resource_id`),
  UNIQUE KEY `uk_robotfactory_projection_code` (`projection_code`),
  UNIQUE KEY `uk_robotfactory_agent_name` (`agent_name`),
  KEY `idx_robotfactory_sync_status` (`sync_status`),
  KEY `idx_robotfactory_school_id` (`school_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='软件工厂资源投影配置表';

CREATE TABLE IF NOT EXISTS `t_robotfactory_sync_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `projection_id` bigint DEFAULT NULL COMMENT '投影ID',
  `resource_id` bigint DEFAULT NULL COMMENT '资源ID',
  `action` varchar(32) NOT NULL COMMENT '同步动作类型',
  `success` tinyint(1) NOT NULL DEFAULT 0 COMMENT '是否成功：1成功 0失败',
  `message` varchar(1000) DEFAULT NULL COMMENT '同步结果说明',
  `request_snapshot_json` longtext DEFAULT NULL COMMENT '同步请求快照JSON',
  `response_snapshot_json` longtext DEFAULT NULL COMMENT '同步响应快照JSON',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (`id`),
  KEY `idx_robotfactory_log_projection` (`projection_id`),
  KEY `idx_robotfactory_log_resource` (`resource_id`),
  KEY `idx_robotfactory_log_action` (`action`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='软件工厂同步日志表';
