-- 将表和字段注释统一修正为中文。
ALTER TABLE `flyway_schema_history` COMMENT = '数据库版本迁移历史表';
ALTER TABLE `t_alert_record` COMMENT = '告警记录表';
ALTER TABLE `t_alert_record_action` COMMENT = '告警记录操作历史表';
ALTER TABLE `t_alert_rule` COMMENT = '告警规则表';
ALTER TABLE `t_announcement` COMMENT = '平台公告表';
ALTER TABLE `t_api_key` COMMENT = '接口密钥表';
ALTER TABLE `t_audit_item` COMMENT = '审核任务表';
ALTER TABLE `t_audit_log` COMMENT = '审计日志表';
ALTER TABLE `t_call_log` COMMENT = '调用日志表';
ALTER TABLE `t_developer_application` COMMENT = '开发者入驻申请表';
ALTER TABLE `t_favorite` COMMENT = '收藏表';
ALTER TABLE `t_integration_package` COMMENT = '集成套餐表';
ALTER TABLE `t_integration_package_item` COMMENT = '集成套餐资源项表';
ALTER TABLE `t_login_history` COMMENT = '登录历史表';
ALTER TABLE `t_notification` COMMENT = '通知表';
ALTER TABLE `t_openai_compat_state` COMMENT = '开放接口兼容状态表';
ALTER TABLE `t_org_menu` COMMENT = '组织架构表';
ALTER TABLE `t_platform_role` COMMENT = '平台角色表';
ALTER TABLE `t_rate_limit_rule` COMMENT = '限流规则表';
ALTER TABLE `t_resource` COMMENT = '统一资源主表';
ALTER TABLE `t_resource_draft` COMMENT = '资源编辑草稿表';
ALTER TABLE `t_resource_relation` COMMENT = '资源关系表';
ALTER TABLE `t_resource_runtime_policy` COMMENT = '资源运行策略表';
ALTER TABLE `t_resource_tag_rel` COMMENT = '资源标签关联表';
ALTER TABLE `t_resource_version` COMMENT = '资源版本表';
ALTER TABLE `t_review` COMMENT = '评论评分表';
ALTER TABLE `t_review_helpful_rel` COMMENT = '评论有用标记表';
ALTER TABLE `t_robotfactory_corp_mapping` COMMENT = '软件工厂学校企业映射表';
ALTER TABLE `t_robotfactory_projection` COMMENT = '软件工厂资源投影配置表';
ALTER TABLE `t_robotfactory_sync_log` COMMENT = '软件工厂同步日志表';
ALTER TABLE `t_sandbox_session` COMMENT = '沙箱会话表';
ALTER TABLE `t_sensitive_word` COMMENT = '敏感词表';
ALTER TABLE `t_system_config` COMMENT = '系统配置表';
ALTER TABLE `t_tag` COMMENT = '标签表';
ALTER TABLE `t_trace_span` COMMENT = '链路追踪片段表';
ALTER TABLE `t_user` COMMENT = '用户表';
ALTER TABLE `t_user_role_rel` COMMENT = '用户角色关联表';
ALTER TABLE `flyway_schema_history` MODIFY COLUMN `installed_rank` int NOT NULL COMMENT '安装顺序';
ALTER TABLE `flyway_schema_history` MODIFY COLUMN `version` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '版本号';
ALTER TABLE `flyway_schema_history` MODIFY COLUMN `description` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '描述';
ALTER TABLE `flyway_schema_history` MODIFY COLUMN `type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '类型';
ALTER TABLE `flyway_schema_history` MODIFY COLUMN `script` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '脚本名称';
ALTER TABLE `flyway_schema_history` MODIFY COLUMN `checksum` int NULL DEFAULT NULL COMMENT '校验值';
ALTER TABLE `flyway_schema_history` MODIFY COLUMN `installed_by` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '安装用户';
ALTER TABLE `flyway_schema_history` MODIFY COLUMN `installed_on` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '安装时间';
ALTER TABLE `flyway_schema_history` MODIFY COLUMN `execution_time` int NOT NULL COMMENT '执行耗时';
ALTER TABLE `flyway_schema_history` MODIFY COLUMN `success` tinyint(1) NOT NULL COMMENT '是否成功';
ALTER TABLE `t_alert_record` MODIFY COLUMN `id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键';
ALTER TABLE `t_alert_record` MODIFY COLUMN `rule_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '规则标识';
ALTER TABLE `t_alert_record` MODIFY COLUMN `rule_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '规则名称';
ALTER TABLE `t_alert_record` MODIFY COLUMN `severity` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '严重级别';
ALTER TABLE `t_alert_record` MODIFY COLUMN `status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '状态';
ALTER TABLE `t_alert_record` MODIFY COLUMN `message` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '消息内容';
ALTER TABLE `t_alert_record` MODIFY COLUMN `source` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '来源';
ALTER TABLE `t_alert_record` MODIFY COLUMN `assignee_user_id` bigint NULL DEFAULT NULL COMMENT '处理人用户标识';
ALTER TABLE `t_alert_record` MODIFY COLUMN `ack_at` datetime NULL DEFAULT NULL COMMENT '确认时间';
ALTER TABLE `t_alert_record` MODIFY COLUMN `silenced_at` datetime NULL DEFAULT NULL COMMENT '静默时间';
ALTER TABLE `t_alert_record` MODIFY COLUMN `reopened_at` datetime NULL DEFAULT NULL COMMENT '重新打开时间';
ALTER TABLE `t_alert_record` MODIFY COLUMN `last_sample_value` decimal(15,4) NULL DEFAULT NULL COMMENT '最近采样值';
ALTER TABLE `t_alert_record` MODIFY COLUMN `trigger_snapshot_json` json NULL COMMENT '触发快照';
ALTER TABLE `t_alert_record` MODIFY COLUMN `rule_snapshot_json` json NULL COMMENT '规则快照';
ALTER TABLE `t_alert_record` MODIFY COLUMN `labels` json NULL COMMENT '标签数据';
ALTER TABLE `t_alert_record` MODIFY COLUMN `fired_at` datetime NOT NULL COMMENT '触发时间';
ALTER TABLE `t_alert_record` MODIFY COLUMN `resolved_at` datetime NULL DEFAULT NULL COMMENT '恢复时间';
ALTER TABLE `t_alert_record_action` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_alert_record_action` MODIFY COLUMN `record_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '记录标识';
ALTER TABLE `t_alert_record_action` MODIFY COLUMN `action_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '操作类型';
ALTER TABLE `t_alert_record_action` MODIFY COLUMN `operator_user_id` bigint NULL DEFAULT NULL COMMENT '操作人用户标识';
ALTER TABLE `t_alert_record_action` MODIFY COLUMN `note` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '备注';
ALTER TABLE `t_alert_record_action` MODIFY COLUMN `previous_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '变更前状态';
ALTER TABLE `t_alert_record_action` MODIFY COLUMN `next_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '变更后状态';
ALTER TABLE `t_alert_record_action` MODIFY COLUMN `extra_json` json NULL COMMENT '扩展数据';
ALTER TABLE `t_alert_record_action` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '名称';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '描述';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `metric` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '指标';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `operator` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '操作符';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `threshold` decimal(15,4) NOT NULL COMMENT '阈值';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `duration` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT '5m' COMMENT '持续时长';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `severity` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '严重级别';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `enabled` tinyint(1) NULL DEFAULT '1' COMMENT '是否启用';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `scope_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'global' COMMENT '范围类型';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `scope_resource_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '范围资源类型';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `scope_resource_id` bigint NULL DEFAULT NULL COMMENT '范围资源标识';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `label_filters` json NULL COMMENT '标签过滤条件';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `notify_channels` json NULL COMMENT '通知渠道';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_alert_rule` MODIFY COLUMN `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_announcement` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_announcement` MODIFY COLUMN `title` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题';
ALTER TABLE `t_announcement` MODIFY COLUMN `summary` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '摘要';
ALTER TABLE `t_announcement` MODIFY COLUMN `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '正文';
ALTER TABLE `t_announcement` MODIFY COLUMN `type` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'notice' COMMENT '类型';
ALTER TABLE `t_announcement` MODIFY COLUMN `pinned` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否置顶';
ALTER TABLE `t_announcement` MODIFY COLUMN `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用';
ALTER TABLE `t_announcement` MODIFY COLUMN `created_by` bigint NULL DEFAULT NULL COMMENT '创建人';
ALTER TABLE `t_announcement` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_announcement` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_announcement` MODIFY COLUMN `deleted` tinyint(1) NOT NULL DEFAULT '0' COMMENT '逻辑删除标记';
ALTER TABLE `t_api_key` MODIFY COLUMN `id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键';
ALTER TABLE `t_api_key` MODIFY COLUMN `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '名称';
ALTER TABLE `t_api_key` MODIFY COLUMN `key_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '密钥哈希';
ALTER TABLE `t_api_key` MODIFY COLUMN `secret_ciphertext` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '加密后的完整密钥';
ALTER TABLE `t_api_key` MODIFY COLUMN `prefix` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '密钥前缀';
ALTER TABLE `t_api_key` MODIFY COLUMN `masked_key` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '脱敏密钥';
ALTER TABLE `t_api_key` MODIFY COLUMN `owner_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '归属类型';
ALTER TABLE `t_api_key` MODIFY COLUMN `owner_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '归属标识';
ALTER TABLE `t_api_key` MODIFY COLUMN `scopes` json NULL COMMENT '权限范围';
ALTER TABLE `t_api_key` MODIFY COLUMN `integration_package_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '集成套餐标识';
ALTER TABLE `t_api_key` MODIFY COLUMN `status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'active' COMMENT '状态';
ALTER TABLE `t_api_key` MODIFY COLUMN `expires_at` datetime NULL DEFAULT NULL COMMENT '过期时间';
ALTER TABLE `t_api_key` MODIFY COLUMN `last_used_at` datetime NULL DEFAULT NULL COMMENT '最近使用时间';
ALTER TABLE `t_api_key` MODIFY COLUMN `call_count` bigint NULL DEFAULT '0' COMMENT '调用次数';
ALTER TABLE `t_api_key` MODIFY COLUMN `created_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '创建人';
ALTER TABLE `t_api_key` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_audit_item` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_audit_item` MODIFY COLUMN `target_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '目标类型';
ALTER TABLE `t_audit_item` MODIFY COLUMN `target_id` bigint NOT NULL COMMENT '目标标识';
ALTER TABLE `t_audit_item` MODIFY COLUMN `display_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '显示名称';
ALTER TABLE `t_audit_item` MODIFY COLUMN `agent_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资源编码';
ALTER TABLE `t_audit_item` MODIFY COLUMN `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '描述';
ALTER TABLE `t_audit_item` MODIFY COLUMN `agent_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_audit_item` MODIFY COLUMN `source_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '来源类型';
ALTER TABLE `t_audit_item` MODIFY COLUMN `audit_kind` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'initial' COMMENT '业务字段';
ALTER TABLE `t_audit_item` MODIFY COLUMN `payload_json` json NULL COMMENT '业务字段';
ALTER TABLE `t_audit_item` MODIFY COLUMN `submitter` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务字段';
ALTER TABLE `t_audit_item` MODIFY COLUMN `submit_time` datetime NOT NULL COMMENT '业务字段';
ALTER TABLE `t_audit_item` MODIFY COLUMN `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'pending_review' COMMENT '状态';
ALTER TABLE `t_audit_item` MODIFY COLUMN `reviewer_id` bigint NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_audit_item` MODIFY COLUMN `reject_reason` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '业务字段';
ALTER TABLE `t_audit_item` MODIFY COLUMN `review_time` datetime NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_audit_item` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_audit_item` MODIFY COLUMN `pending_target_id_guard` bigint NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_audit_item` MODIFY COLUMN `pending_audit_kind_guard` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_audit_log` MODIFY COLUMN `id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键';
ALTER TABLE `t_audit_log` MODIFY COLUMN `user_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用户标识';
ALTER TABLE `t_audit_log` MODIFY COLUMN `username` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用户名';
ALTER TABLE `t_audit_log` MODIFY COLUMN `action` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '操作';
ALTER TABLE `t_audit_log` MODIFY COLUMN `resource` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资源';
ALTER TABLE `t_audit_log` MODIFY COLUMN `resource_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '资源标识';
ALTER TABLE `t_audit_log` MODIFY COLUMN `details` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '详情';
ALTER TABLE `t_audit_log` MODIFY COLUMN `ip` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '网络地址';
ALTER TABLE `t_audit_log` MODIFY COLUMN `user_agent` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户代理';
ALTER TABLE `t_audit_log` MODIFY COLUMN `result` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '结果';
ALTER TABLE `t_audit_log` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_call_log` MODIFY COLUMN `usage_id` bigint NOT NULL AUTO_INCREMENT COMMENT '使用记录序号';
ALTER TABLE `t_call_log` MODIFY COLUMN `id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键';
ALTER TABLE `t_call_log` MODIFY COLUMN `trace_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '链路标识';
ALTER TABLE `t_call_log` MODIFY COLUMN `agent_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资源标识';
ALTER TABLE `t_call_log` MODIFY COLUMN `agent_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资源编码';
ALTER TABLE `t_call_log` MODIFY COLUMN `display_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '显示名称';
ALTER TABLE `t_call_log` MODIFY COLUMN `resource_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '资源类型';
ALTER TABLE `t_call_log` MODIFY COLUMN `user_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用户标识';
ALTER TABLE `t_call_log` MODIFY COLUMN `method` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '请求方法';
ALTER TABLE `t_call_log` MODIFY COLUMN `action` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'invoke' COMMENT '操作';
ALTER TABLE `t_call_log` MODIFY COLUMN `input_preview` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '输入摘要';
ALTER TABLE `t_call_log` MODIFY COLUMN `output_preview` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '输出摘要';
ALTER TABLE `t_call_log` MODIFY COLUMN `status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '状态';
ALTER TABLE `t_call_log` MODIFY COLUMN `status_code` smallint NOT NULL COMMENT '状态码';
ALTER TABLE `t_call_log` MODIFY COLUMN `latency_ms` int NOT NULL COMMENT '延迟毫秒';
ALTER TABLE `t_call_log` MODIFY COLUMN `error_message` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '错误信息';
ALTER TABLE `t_call_log` MODIFY COLUMN `ip` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '网络地址';
ALTER TABLE `t_call_log` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_developer_application` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_developer_application` MODIFY COLUMN `user_id` bigint NOT NULL COMMENT '用户标识';
ALTER TABLE `t_developer_application` MODIFY COLUMN `contact_email` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务字段';
ALTER TABLE `t_developer_application` MODIFY COLUMN `contact_phone` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_developer_application` MODIFY COLUMN `company_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_developer_application` MODIFY COLUMN `apply_reason` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务字段';
ALTER TABLE `t_developer_application` MODIFY COLUMN `status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'pending' COMMENT '状态';
ALTER TABLE `t_developer_application` MODIFY COLUMN `review_comment` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '审核意见';
ALTER TABLE `t_developer_application` MODIFY COLUMN `reviewed_by` bigint NULL DEFAULT NULL COMMENT '审核人';
ALTER TABLE `t_developer_application` MODIFY COLUMN `reviewed_at` datetime NULL DEFAULT NULL COMMENT '审核时间';
ALTER TABLE `t_developer_application` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_developer_application` MODIFY COLUMN `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_developer_application` MODIFY COLUMN `pending_user_guard` bigint NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_favorite` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_favorite` MODIFY COLUMN `user_id` bigint NOT NULL COMMENT '用户标识';
ALTER TABLE `t_favorite` MODIFY COLUMN `target_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '目标类型';
ALTER TABLE `t_favorite` MODIFY COLUMN `target_id` bigint NOT NULL COMMENT '目标标识';
ALTER TABLE `t_favorite` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_integration_package` MODIFY COLUMN `id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键';
ALTER TABLE `t_integration_package` MODIFY COLUMN `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '名称';
ALTER TABLE `t_integration_package` MODIFY COLUMN `description` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '描述';
ALTER TABLE `t_integration_package` MODIFY COLUMN `status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'active' COMMENT '状态';
ALTER TABLE `t_integration_package` MODIFY COLUMN `created_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '创建人';
ALTER TABLE `t_integration_package` MODIFY COLUMN `owner_user_id` bigint NULL DEFAULT NULL COMMENT '归属用户标识';
ALTER TABLE `t_integration_package` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_integration_package` MODIFY COLUMN `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_integration_package_item` MODIFY COLUMN `package_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '套餐标识';
ALTER TABLE `t_integration_package_item` MODIFY COLUMN `resource_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资源类型';
ALTER TABLE `t_integration_package_item` MODIFY COLUMN `resource_id` bigint NOT NULL COMMENT '资源标识';
ALTER TABLE `t_login_history` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_login_history` MODIFY COLUMN `user_id` bigint NOT NULL COMMENT '用户标识';
ALTER TABLE `t_login_history` MODIFY COLUMN `username` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用户名';
ALTER TABLE `t_login_history` MODIFY COLUMN `login_time` datetime NOT NULL COMMENT '登录时间';
ALTER TABLE `t_login_history` MODIFY COLUMN `ip` varchar(45) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '网络地址';
ALTER TABLE `t_login_history` MODIFY COLUMN `user_agent` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '用户代理';
ALTER TABLE `t_login_history` MODIFY COLUMN `login_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务字段';
ALTER TABLE `t_login_history` MODIFY COLUMN `result` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '结果';
ALTER TABLE `t_login_history` MODIFY COLUMN `failure_reason` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_login_history` MODIFY COLUMN `location` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_login_history` MODIFY COLUMN `device` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_login_history` MODIFY COLUMN `os` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_login_history` MODIFY COLUMN `browser` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_notification` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_notification` MODIFY COLUMN `user_id` bigint NOT NULL COMMENT '用户标识';
ALTER TABLE `t_notification` MODIFY COLUMN `type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '类型';
ALTER TABLE `t_notification` MODIFY COLUMN `category` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'notice' COMMENT '分类';
ALTER TABLE `t_notification` MODIFY COLUMN `severity` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'info' COMMENT '严重级别';
ALTER TABLE `t_notification` MODIFY COLUMN `title` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '标题';
ALTER TABLE `t_notification` MODIFY COLUMN `body` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '业务字段';
ALTER TABLE `t_notification` MODIFY COLUMN `source_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '来源类型';
ALTER TABLE `t_notification` MODIFY COLUMN `source_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '来源标识';
ALTER TABLE `t_notification` MODIFY COLUMN `aggregate_key` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '聚合键';
ALTER TABLE `t_notification` MODIFY COLUMN `flow_status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_notification` MODIFY COLUMN `current_step` int NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_notification` MODIFY COLUMN `total_steps` int NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_notification` MODIFY COLUMN `steps_json` json NULL COMMENT '业务字段';
ALTER TABLE `t_notification` MODIFY COLUMN `action_label` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_notification` MODIFY COLUMN `action_url` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_notification` MODIFY COLUMN `metadata_json` json NULL COMMENT '业务字段';
ALTER TABLE `t_notification` MODIFY COLUMN `is_read` tinyint(1) NULL DEFAULT '0' COMMENT '业务字段';
ALTER TABLE `t_notification` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_notification` MODIFY COLUMN `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_notification` MODIFY COLUMN `last_event_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '业务字段';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `object_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '对象类型';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `owner_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '归属类型';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `owner_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '归属标识';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `parent_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '父级标识';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `assistant_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '助手标识';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `role` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '角色';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `model_alias` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '模型别名';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `status` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '状态';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '名称';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `instructions` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '指令内容';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `content_text` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '文本内容';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `content_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '内容数据';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `output_text` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '输出文本';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `created_at` bigint NOT NULL COMMENT '创建时间';
ALTER TABLE `t_openai_compat_state` MODIFY COLUMN `updated_at` bigint NOT NULL COMMENT '更新时间';
ALTER TABLE `t_org_menu` MODIFY COLUMN `menu_id` bigint NOT NULL AUTO_INCREMENT COMMENT '组织标识';
ALTER TABLE `t_org_menu` MODIFY COLUMN `menu_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '组织名称';
ALTER TABLE `t_org_menu` MODIFY COLUMN `menu_parent_id` bigint NULL DEFAULT '0' COMMENT '父级组织标识';
ALTER TABLE `t_org_menu` MODIFY COLUMN `menu_level` smallint NOT NULL COMMENT '业务字段';
ALTER TABLE `t_org_menu` MODIFY COLUMN `if_xy` smallint NULL DEFAULT '0' COMMENT '业务字段';
ALTER TABLE `t_org_menu` MODIFY COLUMN `head_count` int NULL DEFAULT '0' COMMENT '人数';
ALTER TABLE `t_org_menu` MODIFY COLUMN `sort_order` int NULL DEFAULT '0' COMMENT '排序值';
ALTER TABLE `t_org_menu` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_org_menu` MODIFY COLUMN `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_platform_role` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_platform_role` MODIFY COLUMN `role_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '角色编码';
ALTER TABLE `t_platform_role` MODIFY COLUMN `role_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '角色名称';
ALTER TABLE `t_platform_role` MODIFY COLUMN `description` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '描述';
ALTER TABLE `t_platform_role` MODIFY COLUMN `permissions` json NOT NULL COMMENT '权限集合';
ALTER TABLE `t_platform_role` MODIFY COLUMN `is_system` tinyint(1) NULL DEFAULT '0' COMMENT '业务字段';
ALTER TABLE `t_platform_role` MODIFY COLUMN `user_count` int NULL DEFAULT '0' COMMENT '用户数量';
ALTER TABLE `t_platform_role` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_platform_role` MODIFY COLUMN `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '名称';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `target` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务字段';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `target_value` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `resource_scope` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `window_ms` bigint NOT NULL COMMENT '业务字段';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `max_requests` int NOT NULL COMMENT '业务字段';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `max_tokens` int NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `burst_limit` int NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `action` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '操作';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `enabled` tinyint(1) NULL DEFAULT '1' COMMENT '是否启用';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `priority` int NULL DEFAULT '0' COMMENT '业务字段';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_rate_limit_rule` MODIFY COLUMN `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_resource` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_resource` MODIFY COLUMN `resource_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资源类型';
ALTER TABLE `t_resource` MODIFY COLUMN `resource_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资源编码';
ALTER TABLE `t_resource` MODIFY COLUMN `display_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '显示名称';
ALTER TABLE `t_resource` MODIFY COLUMN `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '描述';
ALTER TABLE `t_resource` MODIFY COLUMN `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'draft' COMMENT '状态';
ALTER TABLE `t_resource` MODIFY COLUMN `source_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '来源类型';
ALTER TABLE `t_resource` MODIFY COLUMN `access_policy` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'grant_required' COMMENT '访问策略';
ALTER TABLE `t_resource` MODIFY COLUMN `view_count` bigint NOT NULL DEFAULT '0' COMMENT '浏览次数';
ALTER TABLE `t_resource` MODIFY COLUMN `is_public` tinyint(1) NULL DEFAULT NULL COMMENT '是否公开';
ALTER TABLE `t_resource` MODIFY COLUMN `service_detail_md` mediumtext CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '服务详情';
ALTER TABLE `t_resource` MODIFY COLUMN `detail_json` json NULL COMMENT '扩展配置';
ALTER TABLE `t_resource` MODIFY COLUMN `created_by` bigint NULL DEFAULT NULL COMMENT '创建人';
ALTER TABLE `t_resource` MODIFY COLUMN `deleted` smallint NULL DEFAULT '0' COMMENT '逻辑删除标记';
ALTER TABLE `t_resource` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_resource` MODIFY COLUMN `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_resource_draft` MODIFY COLUMN `resource_id` bigint NOT NULL COMMENT '资源标识';
ALTER TABLE `t_resource_draft` MODIFY COLUMN `draft_json` json NOT NULL COMMENT '草稿数据';
ALTER TABLE `t_resource_draft` MODIFY COLUMN `audit_tier` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'medium' COMMENT '审核等级';
ALTER TABLE `t_resource_draft` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_resource_relation` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_resource_relation` MODIFY COLUMN `from_resource_id` bigint NOT NULL COMMENT '来源资源标识';
ALTER TABLE `t_resource_relation` MODIFY COLUMN `to_resource_id` bigint NOT NULL COMMENT '目标资源标识';
ALTER TABLE `t_resource_relation` MODIFY COLUMN `relation_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '关系类型';
ALTER TABLE `t_resource_relation` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `resource_id` bigint NOT NULL COMMENT '资源标识';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `resource_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资源类型';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `resource_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资源编码';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `display_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '显示名称';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `check_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'http' COMMENT '检查类型';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `check_url` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '检查地址';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `interval_sec` int NULL DEFAULT '30' COMMENT '间隔秒数';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `healthy_threshold` int NULL DEFAULT '3' COMMENT '健康阈值';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `timeout_sec` int NULL DEFAULT '10' COMMENT '超时秒数';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `probe_strategy` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'http' COMMENT '探测策略';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `probe_config_json` json NULL COMMENT '探测配置';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `canary_payload_json` json NULL COMMENT '金丝雀请求数据';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `health_status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'healthy' COMMENT '健康状态';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `last_check_time` datetime NULL DEFAULT NULL COMMENT '最近检查时间';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `last_probe_at` datetime NULL DEFAULT NULL COMMENT '最近探测时间';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `last_success_at` datetime NULL DEFAULT NULL COMMENT '最近成功时间';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `last_failure_at` datetime NULL DEFAULT NULL COMMENT '最近失败时间';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `last_failure_reason` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '最近失败原因';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `consecutive_success` bigint NULL DEFAULT '0' COMMENT '连续成功次数';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `consecutive_failure` bigint NULL DEFAULT '0' COMMENT '连续失败次数';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `probe_latency_ms` bigint NULL DEFAULT NULL COMMENT '探测延迟毫秒';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `probe_payload_summary` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '探测结果摘要';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `last_probe_evidence_json` json NULL COMMENT '最近探测证据';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `current_state` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'CLOSED' COMMENT '当前状态';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `callability_state` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'not_configured' COMMENT '可调用状态';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `callability_reason` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '可调用原因';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `failure_threshold` int NULL DEFAULT '5' COMMENT '失败阈值';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `open_duration_sec` int NULL DEFAULT '60' COMMENT '开启持续秒数';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `half_open_max_calls` int NULL DEFAULT '3' COMMENT '半开最大调用数';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `fallback_resource_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '降级资源编码';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `fallback_message` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '降级消息';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `last_opened_at` datetime NULL DEFAULT NULL COMMENT '最近开启时间';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `success_count` bigint NULL DEFAULT '0' COMMENT '成功次数';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `failure_count` bigint NULL DEFAULT '0' COMMENT '失败次数';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_resource_runtime_policy` MODIFY COLUMN `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_resource_tag_rel` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_resource_tag_rel` MODIFY COLUMN `resource_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '资源类型';
ALTER TABLE `t_resource_tag_rel` MODIFY COLUMN `resource_id` bigint NOT NULL COMMENT '资源标识';
ALTER TABLE `t_resource_tag_rel` MODIFY COLUMN `tag_id` bigint NOT NULL COMMENT '标签标识';
ALTER TABLE `t_resource_tag_rel` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_resource_version` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_resource_version` MODIFY COLUMN `resource_id` bigint NOT NULL COMMENT '资源标识';
ALTER TABLE `t_resource_version` MODIFY COLUMN `version` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '版本号';
ALTER TABLE `t_resource_version` MODIFY COLUMN `status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'active' COMMENT '状态';
ALTER TABLE `t_resource_version` MODIFY COLUMN `is_current` tinyint(1) NULL DEFAULT '0' COMMENT '是否当前版本';
ALTER TABLE `t_resource_version` MODIFY COLUMN `snapshot_json` json NULL COMMENT '快照数据';
ALTER TABLE `t_resource_version` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_review` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_review` MODIFY COLUMN `target_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '目标类型';
ALTER TABLE `t_review` MODIFY COLUMN `target_id` bigint NOT NULL COMMENT '目标标识';
ALTER TABLE `t_review` MODIFY COLUMN `parent_id` bigint NULL DEFAULT NULL COMMENT '父级标识';
ALTER TABLE `t_review` MODIFY COLUMN `user_id` bigint NOT NULL COMMENT '用户标识';
ALTER TABLE `t_review` MODIFY COLUMN `user_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务字段';
ALTER TABLE `t_review` MODIFY COLUMN `avatar` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_review` MODIFY COLUMN `rating` smallint NOT NULL COMMENT '评分';
ALTER TABLE `t_review` MODIFY COLUMN `comment` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '评论';
ALTER TABLE `t_review` MODIFY COLUMN `helpful_count` int NULL DEFAULT '0' COMMENT '有用数';
ALTER TABLE `t_review` MODIFY COLUMN `deleted` smallint NULL DEFAULT '0' COMMENT '逻辑删除标记';
ALTER TABLE `t_review` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_review_helpful_rel` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_review_helpful_rel` MODIFY COLUMN `review_id` bigint NOT NULL COMMENT '评论标识';
ALTER TABLE `t_review_helpful_rel` MODIFY COLUMN `user_id` bigint NOT NULL COMMENT '用户标识';
ALTER TABLE `t_review_helpful_rel` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_robotfactory_corp_mapping` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_robotfactory_corp_mapping` MODIFY COLUMN `school_id` bigint NOT NULL COMMENT '学校标识';
ALTER TABLE `t_robotfactory_corp_mapping` MODIFY COLUMN `school_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_corp_mapping` MODIFY COLUMN `corp_id` bigint NOT NULL COMMENT '企业标识';
ALTER TABLE `t_robotfactory_corp_mapping` MODIFY COLUMN `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用';
ALTER TABLE `t_robotfactory_corp_mapping` MODIFY COLUMN `remark` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '备注';
ALTER TABLE `t_robotfactory_corp_mapping` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_robotfactory_corp_mapping` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `resource_id` bigint NOT NULL COMMENT '资源标识';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `resource_type` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'mcp' COMMENT '资源类型';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `projection_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `school_id` bigint NULL DEFAULT NULL COMMENT '学校标识';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `corp_id` bigint NULL DEFAULT NULL COMMENT '企业标识';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `scope_mode` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'school' COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `agent_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '资源编码';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `display_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '显示名称';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '描述';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `display_name_override` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `description_override` text CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `display_template` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `display_template_override` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `agent_type` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'mcp' COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `mode` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'TOOL' COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `runtime_role` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT 'tool' COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `interaction_mode` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT 'sync' COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `dispatch_mode` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT 'tool_sync' COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `spec_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `spec_json_override` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `parameters_schema` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `parameters_schema_override` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `auto_sync_enabled` tinyint(1) NOT NULL DEFAULT '0' COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `external_agent_id` bigint NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `sync_status` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL DEFAULT 'pending' COMMENT '同步状态';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `sync_message` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '同步消息';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `last_synced_at` datetime NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_robotfactory_projection` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_robotfactory_sync_log` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_robotfactory_sync_log` MODIFY COLUMN `projection_id` bigint NULL DEFAULT NULL COMMENT '投影标识';
ALTER TABLE `t_robotfactory_sync_log` MODIFY COLUMN `resource_id` bigint NULL DEFAULT NULL COMMENT '资源标识';
ALTER TABLE `t_robotfactory_sync_log` MODIFY COLUMN `action` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '操作';
ALTER TABLE `t_robotfactory_sync_log` MODIFY COLUMN `success` tinyint(1) NOT NULL DEFAULT '0' COMMENT '是否成功';
ALTER TABLE `t_robotfactory_sync_log` MODIFY COLUMN `message` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL DEFAULT NULL COMMENT '消息内容';
ALTER TABLE `t_robotfactory_sync_log` MODIFY COLUMN `request_snapshot_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_sync_log` MODIFY COLUMN `response_snapshot_json` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NULL COMMENT '业务字段';
ALTER TABLE `t_robotfactory_sync_log` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `session_token` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务字段';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `owner_user_id` bigint NOT NULL COMMENT '归属用户标识';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `api_key_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务字段';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `api_key_prefix` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'active' COMMENT '状态';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `allowed_resource_types` json NULL COMMENT '业务字段';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `max_calls` int NOT NULL DEFAULT '100' COMMENT '业务字段';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `used_calls` int NOT NULL DEFAULT '0' COMMENT '业务字段';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `max_timeout_sec` int NOT NULL DEFAULT '30' COMMENT '业务字段';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `expires_at` datetime NOT NULL COMMENT '过期时间';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `last_invoke_at` datetime NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_sandbox_session` MODIFY COLUMN `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_sensitive_word` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_sensitive_word` MODIFY COLUMN `word` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '敏感词';
ALTER TABLE `t_sensitive_word` MODIFY COLUMN `category` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'default' COMMENT '分类';
ALTER TABLE `t_sensitive_word` MODIFY COLUMN `severity` int NOT NULL DEFAULT '1' COMMENT '严重级别';
ALTER TABLE `t_sensitive_word` MODIFY COLUMN `source` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'manual' COMMENT '来源';
ALTER TABLE `t_sensitive_word` MODIFY COLUMN `enabled` tinyint(1) NOT NULL DEFAULT '1' COMMENT '是否启用';
ALTER TABLE `t_sensitive_word` MODIFY COLUMN `created_by` bigint NULL DEFAULT NULL COMMENT '创建人';
ALTER TABLE `t_sensitive_word` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_sensitive_word` MODIFY COLUMN `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_system_config` MODIFY COLUMN `id` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键';
ALTER TABLE `t_system_config` MODIFY COLUMN `scope` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '业务字段';
ALTER TABLE `t_system_config` MODIFY COLUMN `config_key` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '配置键';
ALTER TABLE `t_system_config` MODIFY COLUMN `config_value` text CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL COMMENT '配置值';
ALTER TABLE `t_system_config` MODIFY COLUMN `value_type` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL DEFAULT 'string' COMMENT '业务字段';
ALTER TABLE `t_system_config` MODIFY COLUMN `label` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_system_config` MODIFY COLUMN `description` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '描述';
ALTER TABLE `t_system_config` MODIFY COLUMN `category` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '分类';
ALTER TABLE `t_system_config` MODIFY COLUMN `editable` tinyint(1) NOT NULL DEFAULT '1' COMMENT '业务字段';
ALTER TABLE `t_system_config` MODIFY COLUMN `options_json` json NULL COMMENT '业务字段';
ALTER TABLE `t_system_config` MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_system_config` MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_tag` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_tag` MODIFY COLUMN `name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '名称';
ALTER TABLE `t_tag` MODIFY COLUMN `category` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '分类';
ALTER TABLE `t_tag` MODIFY COLUMN `usage_count` int NULL DEFAULT '0' COMMENT '业务字段';
ALTER TABLE `t_tag` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_trace_span` MODIFY COLUMN `id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '主键';
ALTER TABLE `t_trace_span` MODIFY COLUMN `trace_id` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '链路标识';
ALTER TABLE `t_trace_span` MODIFY COLUMN `parent_id` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '父级标识';
ALTER TABLE `t_trace_span` MODIFY COLUMN `operation_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '操作名称';
ALTER TABLE `t_trace_span` MODIFY COLUMN `service_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '服务名称';
ALTER TABLE `t_trace_span` MODIFY COLUMN `start_time` datetime NOT NULL COMMENT '开始时间';
ALTER TABLE `t_trace_span` MODIFY COLUMN `duration` int NOT NULL COMMENT '持续时长';
ALTER TABLE `t_trace_span` MODIFY COLUMN `status` varchar(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '状态';
ALTER TABLE `t_trace_span` MODIFY COLUMN `tags` json NULL COMMENT '标签数据';
ALTER TABLE `t_trace_span` MODIFY COLUMN `logs` json NULL COMMENT '日志数据';
ALTER TABLE `t_user` MODIFY COLUMN `user_id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户标识';
ALTER TABLE `t_user` MODIFY COLUMN `username` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '用户名';
ALTER TABLE `t_user` MODIFY COLUMN `password_hash` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '密码哈希';
ALTER TABLE `t_user` MODIFY COLUMN `real_name` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL COMMENT '真实姓名';
ALTER TABLE `t_user` MODIFY COLUMN `sex` smallint NULL DEFAULT '0' COMMENT '性别';
ALTER TABLE `t_user` MODIFY COLUMN `school_id` bigint NOT NULL COMMENT '学校标识';
ALTER TABLE `t_user` MODIFY COLUMN `menu_id` bigint NULL DEFAULT NULL COMMENT '组织标识';
ALTER TABLE `t_user` MODIFY COLUMN `major` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '业务字段';
ALTER TABLE `t_user` MODIFY COLUMN `class` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '班级';
ALTER TABLE `t_user` MODIFY COLUMN `role` smallint NOT NULL DEFAULT '0' COMMENT '角色';
ALTER TABLE `t_user` MODIFY COLUMN `mobile` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '手机号';
ALTER TABLE `t_user` MODIFY COLUMN `mail` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '邮箱';
ALTER TABLE `t_user` MODIFY COLUMN `head_image` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '头像';
ALTER TABLE `t_user` MODIFY COLUMN `zw` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '职务';
ALTER TABLE `t_user` MODIFY COLUMN `zc` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT NULL COMMENT '职称';
ALTER TABLE `t_user` MODIFY COLUMN `birthday` date NULL DEFAULT NULL COMMENT '生日';
ALTER TABLE `t_user` MODIFY COLUMN `status` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'active' COMMENT '状态';
ALTER TABLE `t_user` MODIFY COLUMN `last_login_time` datetime NULL DEFAULT NULL COMMENT '最近登录时间';
ALTER TABLE `t_user` MODIFY COLUMN `deleted` smallint NULL DEFAULT '0' COMMENT '逻辑删除标记';
ALTER TABLE `t_user` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE `t_user` MODIFY COLUMN `update_time` datetime NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间';
ALTER TABLE `t_user` MODIFY COLUMN `language` varchar(16) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NULL DEFAULT 'zh-CN' COMMENT '语言';
ALTER TABLE `t_user_role_rel` MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键';
ALTER TABLE `t_user_role_rel` MODIFY COLUMN `user_id` bigint NOT NULL COMMENT '用户标识';
ALTER TABLE `t_user_role_rel` MODIFY COLUMN `role_id` bigint NOT NULL COMMENT '角色标识';
ALTER TABLE `t_user_role_rel` MODIFY COLUMN `create_time` datetime NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
